### ISSUE TITLE
Link Header case broke getV1BatchTokenFromHeaders

### ISSUE THREAD

**Issue by thunberg** [square/connect-php-sdk#101]
getV1BatchTokenFromHeaders fails to parse the batch token using headers returned from a V1TransactionsApi listPaymentsWithHttpInfo call since it looks for isset($http_headers['Link']) and headers are now returned lowercase.

To be clear, a one character workaround is isset($http_headers['link']) on line 289 in ApiClient (note lowercase "link").

Any suggestions?

**Comment by StephenJosey** [comment]
Thanks for reporting! We'll take a look. To get around this, feel free to download the SDK repo locally and use it instead of via Composer etc, and make the change in your local SDK so it correctly retrieves the link header.

I'll update this once we actually resolve this or have more information, though.

**Comment by StephenJosey** [comment]
Just heard back from internal teams, this should be resolved now. Please let me know if you're still experiencing it, though.

**Comment by thunberg** [comment]
Thank you for the reply, but still coming through lowercase for me.

**Comment by StephenJosey** [comment]
...try again! No, seriously, we realized we missed a spot, and this should now _really_ be resolved 😄. Sorry for the confusion, but appreciate you letting us know. Definitely let us know if you have any further issues or questions in the future!
