### ISSUE TITLE
how to validate checkout?

### ISSUE THREAD

**Issue by cpeker** [square/connect-php-sdk#105]
Hi,
After redirect_url is triggered, i only have checkoutid and transactionid.

I didn't find a way to validate any of these.
How can i validate checkoutId or transactionId?

**Comment by sseaman** [comment]
@cpeker - Do you still require some help or were you able to determine how to do things?

**Comment by StephenJosey** [comment]
Just to clarify for anyone else: `transactionId` == `orderId` (since Transactions API is deprecated). You can use this `transactionId` to pass to the `BatchRetrieveOrders` endpoint and find information about the transaction, such as if it was paid, or what items were in the order etc. 

Closing out but please comment if you have additional questions.
