### ISSUE TITLE
Unable to add locationId in sqpayment form - ChallengeParameters is not defined

### ISSUE THREAD

**Issue by raza-jahangir** [square/connect-php-sdk#127]
I was using the sqpaymentform without locationId but for buyerVerification I am required to use it. As i Add it I receive the following errors in the console.

Uncaught ReferenceError: ChallengeParameters is not defined
    at Object.<anonymous> ((index):363)
    at Object.1 ((index):371)
    at t ((index):1)data.js:15 
    at (index):1
    at Object.2.../../build/libs/3ds2-widget-js-1.0.138035.js ((index):372)
    at t ((index):1)
    at va ((index):1)
    at (index):1

Uncaught TypeError: t.load is not a function
    at HTMLScriptElement.i.onload (data.js:15)

**Comment by StephenJosey** [comment]
Hey @raza-jahangir I believe we spoke on BuildWithSquare, but just wanted to close the loop here. We've added some code on Square's side to not break the payment form if the `ChallengeParameters` is not defined, but ultimately it seemed like it wasn't defined due to the partnership (WP Easy Pay) possibly had a bug since we were unable to replicate it. I'll close this issue out since we've made a change on our end, but please re-open if you feel otherwise. Thank you for reporting!
