### ISSUE TITLE
How to get customer_id

### ISSUE THREAD

**Issue by jerryseigle** [square/connect-php-sdk#24]
I need a php script to get customer_id.
I used the script to create customer card. It ask for the customer_id. Is there a script which can get the customer_id by first and last name

**Comment by tristansokol** [comment]
Hi @jerryseigle, 
It looks like you have more of a support question here, rather than an issue to report. [Stack Overflow](https://stackoverflow.com/questions/tagged/square-connect) is probably a better place for your support questions in the future. 

You should use the [List Customer](https://github.com/square/connect-php-sdk/blob/master/docs/Api/CustomersApi.md#listcustomers) endpoint and search for the customer you want, you cannot query.
