### ISSUE TITLE
CHANGES.md not updated & minimal release notes despite breaking changes

### ISSUE THREAD

**Issue by ziemkowski** [square/connect-php-sdk#33]
The 2.1.0 release renamed TransactionApi to Transaction**s**API (making it plural) but there are zero notices about this. That class's `charge()` method also removed the first argument. This seems like the most important method in the entire SDK, but the [Releases entry](https://github.com/square/connect-php-sdk/releases/tag/2.1.0) is blank.

Please, please, at the very least update `CHANGES.md` with at least breaking changes, even if they're due to changes in the endpoint (as [this breaking change](https://github.com/square/connect-php-sdk/pull/18/commits/185cd37bf0352a7f6013ddfe73edc359c6c0fc17) was), or delete the file if it isn't going to be maintained.

**Comment by jpirkey** [comment]
Exactly! Based on [Semantic Versioning](http://semver.org/), there should be no backwards incompatible changes in a minor version.

>MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**Comment by bunnyc1986** [comment]
We use the API version for the MAJOR version. Because our latest API is Connect V2, so we use 2 for MAJOR version.
2.1.0 release was exception, the API grouping was updated on the API side, so the generated SDK was also updated with new namespaces. But we totally understand this is a breaking change, and it won't happen in future without explicit early announcement.
