### ISSUE TITLE
Tickets API

### ISSUE THREAD

**Issue by newelement** [square/connect-php-sdk#81]
Will tickets be supported in the API soon? I have a shop repair app I've built and would like the ability to push tickets to the square API so they can show up in my Square Register POS.

**Comment by StephenJosey** [comment]
You are able to push orders to the POS, now. The orders push feature is currently in open beta and only available on iPads. Within a `CreateOrder` request, you can pass in a `fulfillments` field. Once the order has been passed to the `Charge` endpoint, it will show up in the Square POS. Since it's in beta, we don't have long form documentation at this time, and I highly recommend you to join our [Slack](squ.re/slack) community, as we have a channel dedicated to this feature (#orders-push-beta).

For more information about the the actual implementation, please see our tech ref on `CreateOrder`: https://docs.connect.squareup.com/api/connect/v2#endpoint-orders-createorder

**Comment by newelement** [comment]
So by creating an order I should see the ticket show up in my Square Register POS correct? Or are you saying it won't because it will only work for iPads?

**Comment by StephenJosey** [comment]
Hey @newelement sorry about that, I misread and didn't realize you already pointed out you were using Square Register. In that case, since it's an Android device, it will not work unfortunately. This feature is currently in beta and the team is constantly working on making it better, but at this time it will not work. We do not currently have any public timelines on future updates, so I can't say if or when it will be released for Square Register.

**Comment by newelement** [comment]
Thanks for the update. Will look forward to the feature, it will save a lot of time.
