### ISSUE TITLE
MANUAL_ADJUST adjustment type is adding instead of overriding the current stock

### ISSUE THREAD

**Issue by TravisCornelius** [square/connect-php-sdk#84]
Configure OAuth2 access token for authorization: oauth2
    SquareConnect\Configuration::getDefaultConfiguration()->setAccessToken(API_KEY_SQUARE);

    $api_instance = new SquareConnect\Api\V1ItemsApi();
    $body = new \SquareConnect\Model\V1AdjustInventoryRequest(); // \SquareConnect\Model\V1AdjustInventoryRequest | An object containing the fields to POST for the request.  See the corresponding object definition for field details.

    $body->setQuantityDelta($value);
    $body->setAdjustmentType("MANUAL_ADJUST");

doesn't work

**Comment by StephenJosey** [comment]
Hey @TravisCornelius are you receiving an error? In the title you mention it adds instead of overrides, but in the body you say it just doesn't work. 

Just to clarify: it's meant to add instead of override (that's why we call it a delta value, implying it's the difference, not the new amount). So if that's the issue, then it is not an issue (it works properly). However, if you're actually not able to get it to work, can you provide any errors you're receiving?

**Comment by TravisCornelius** [comment]
Works properly then, I just figured it should override, since the same result can be done via sale or recieved enums
